# Site settings
title: Vector's Blog
email: 642280620@qq.com
description: "Python,HTML,CSS,Machine Leaning"
permalink: /:year/:month/:day/:title.html
baseurl: ""
author: "vector"

# Build settings
# permalink: date

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [fenced_code_blocks,no_intra_emphasis,strikethrough,no_intra_emphasis,autolink,tables]

navigations:
  - title: 分类
    class: fa fa-user
    href: /categories/
  - title: 标签
    class: fa fa-film
    href: /tags/
